version: "3.3"

services:
  web:
    build: .
    container_name: markdown-notes
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - "./notes:/usr/app/notes:rw"
    environment:
      HOST: "0.0.0.0"
